<?php

return [
    'WIREGUARD_CIDR_RANGE' => env("WIREGUARD_CIDR_RANGE"),
    'WIREGUARD_INTERFACE' => env('WIREGUARD_INTERFACE'),
    'WIREGUARD_PRIVATE_KEY' => env("WIREGUARD_PRIVATE_KEY"),
    'WIREGUARD_PUBLIC_KEY' => env('WIREGUARD_PUBLIC_KEY'),
    'WIREGUARD_PUBLIC_IP' => env('WIREGUARD_PUBLIC_IP'),
    'WIREGUARD_LISTEN_PORT' => env('WIREGUARD_LISTEN_PORT'),
    'WIREGUARD_INTERFACE_IP' => env('WIREGUARD_INTERFACE_IP'),
    'WIREGUARD_USERNAME' => env('WIREGUARD_USERNAME'),
    'WIREGUARD_PASSWORD' => env('WIREGUARD_PASSWORD')
];
